### ISSUE TITLE
Build failure: whenKafkaPublishTimeoutThenCircuitIsOpened FAILED

### ISSUE THREAD

**Issue by peteraba** [zalando/nakadi#741]
I'm absolutely newbie here, I just tried to follow the README and the build seems to be broken:

```
org.zalando.nakadi.repository.kafka.KafkaTopicRepositoryTest > whenKafkaPublishTimeoutThenCircuitIsOpened FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.zalando.nakadi.repository.kafka.KafkaTopicRepositoryTest.whenKafkaPublishTimeoutThenCircuitIsOpened(KafkaTopicRepositoryTest.java:355)
```

I'm not sure what information you might need so I'll just share the obvious.
```
➤ java -version
openjdk version "1.8.0_144"
OpenJDK Runtime Environment (build 1.8.0_144-b01)
OpenJDK 64-Bit Server VM (build 25.144-b01, mixed mode)

➤ gradle -version

------------------------------------------------------------
Gradle 4.0.2
------------------------------------------------------------

Build time:   2017-07-26 15:04:56 UTC
Revision:     108c593aa7b43852f39045337ee84ee1d87c87fd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Linux 4.9.43-1-MANJARO amd64
```

Let me know if you need anything else.

**Comment by adyach** [comment]
@peteraba good day, could you tell me how you run it? we have not tested it against gradle 4.0.2

**Comment by peteraba** [comment]
@adyach I just installed gradle via pacman and ran './gradlew build' as mentioned by the README.

**Comment by peteraba** [comment]
As discussed privately, this appears to be a flakey test, it passed 3 out 6 times for me, every time running the whole test suite.

**Comment by lmontrieux** [comment]
Thanks for reporting this bug, @peteraba . We'll prioritise it and fix it as soon as possible.

**Comment by peteraba** [comment]
@lmontrieux @adyach: good luck guys, ping me if you need more info!
